---
ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    world_frame: "odom"
    odom_frame: "odom"
    base_link_frame: "base_link"
    map_frame: "map"
    publish_tf: true
    publish_acceleration: false
    
    odom0: "odometry_topic_1"
    odom1: "odometry_topic_2"
    
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    
    odom1_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]

    odom0_differential: false
    odom1_differential: false
    odom0_relative: false
    odom1_relative: false
    
    odom0_queue_size: 10
    odom1_queue_size: 10    